spring: 
  application: 
    name: tongplatform-business-content
  redis:
   database: 2
   cluster:
      nodes: 192.168.203.65:8000,192.168.203.65:8001,192.168.203.65:8002,192.168.203.65:8003,192.168.203.65:8004,192.168.203.65:8005
   pool:
      max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: -1      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 10      # 连接池中的最大空闲连接
      min-idle: 5       # 连接池中的最小空闲连接   
    
server: 
  port: 9401
eureka: 
  client: 
    serviceUrl:
      defaultZone: http://127.0.0.1:9010/eureka/

jdbc:
   url: jdbc:mysql://192.168.203.68:3306/tong-common?useUnicode=true&characterEncoding=UTF-8
   driverName: com.mysql.jdbc.Driver
   username: root
   password: innoChinaAdmin
   initialSize: 1
   minIdle: 1
   maxActive: 200
   maxWait: 60000
   timeBetweenEvictionRunsMillis: 60000
   minEvictableIdleTimeMillis: 300000
   validationQuery: SELECT 'x'

mybatis:
   dbType: mysql
   aliasesPackege: com.**.autogenerator.entity
   mapperBasePackage: com.**.autogenerator.mapper
   mapper-locations: classpath*:mapperxml/**/*.xml

article:
  #服务协议Id
  service: 1232130213
  #关于我们Id
  aboutus: 3123123213312
  ##资讯分类Id
  categoryId: 76ccda9d409648d0b7c9c00527d6de33
  ##资讯s分类eq
  categorySeq : 00010002

   
